### ISSUE TITLE
AttributeError: 'IndexBatchSamplerWrapper' object has no attribute '_batch_sampler'

### ISSUE THREAD

**Issue by Bo-UT** [CSOgroup/torchgmm#4]
### Report

Hi, 

Thanks for the nice tool. 
I got AttributeError when running cellcharter. I installed cellcharter by 

`pip install git+https://github.com/CSOgroup/cellcharter `

It runs well before. It seems the torchgmm issue. Please see following:

![Screenshot 2024-10-03 at 4 32 37 PM](https://github.com/user-attachments/assets/6df5ca7b-cd85-4fcc-a65f-eab974860c46)

Thank you. 

### Version information

-----
session_info        1.0.0
-----
asttokens           NA
comm                0.2.2
cython_runtime      NA
dateutil            2.9.0
debugpy             1.8.6
decorator           5.1.1
exceptiongroup      1.2.2
executing           2.1.0
ipykernel           6.29.5
jedi                0.19.1
packaging           24.1
parso               0.8.4
pickleshare         0.7.5
platformdirs        4.3.6
prompt_toolkit      3.0.48
psutil              6.0.0
pure_eval           0.2.3
pydev_ipython       NA
pydevconsole        NA
pydevd              3.1.0
pydevd_file_utils   NA
pydevd_plugins      NA
pydevd_tracing      NA
pygments            2.18.0
six                 1.16.0
stack_data          0.6.2
tornado             6.4.1
traitlets           5.14.3
typing_extensions   NA
vscode              NA
wcwidth             0.2.13
zmq                 26.2.0
-----
IPython             8.28.0
jupyter_client      8.6.3
jupyter_core        5.7.2
-----
Python 3.10.15 | packaged by conda-forge | (main, Sep 30 2024, 17:51:04) [GCC 13.3.0]
Linux-6.5.0-35-generic-x86_64-with-glibc2.35
-----
Session information updated at 2024-10-03 16:49

**Comment by marcovarrone** [comment]
Hi @Bo-UT,
What's the version of pytorch_lightning you have installed?

**Comment by Bo-UT** [comment]
Thanks for the prompt response. 
Its 1.9.5.

**Comment by marcovarrone** [comment]
That's probably why!
I looked into PyTorch lightning and before v2.0.0 that variable was called `_sampler` instead of `_batch_sampler`. 
If you can, the most straightforward solution would be to update pytorch-lightning to version >= 0.2.0.
I will change the requirements of the package to reflect that.

Thank you very much for the feedback

**Comment by Bo-UT** [comment]
Thank you! I installed 2.1.0, but got an incompatible error: 

`scvi-tools 0.20.3 requires pytorch-lightning<1.10.0,>=1.9.0, but you have pytorch-lightning 2.1.0 which is incompatible.`

Do you have a specific version of `scvi-tools` compatible to current version of `cellcharter`? Here is the full list of installed packages: 

<details>
  <summary>dependencies:</summary>

  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backports=1.1=pyhd3eb1b0_1
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.8.6=py310hf71b8c6_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.28.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_1
  - libedit=3.1.20191231=he28a2e2_2
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgomp=14.1.0=h77fa898_1
  - libnsl=2.0.1=hd590300_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.46.1=hadc24fc_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=pyh8b19718_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=6.0.0=py310ha75aee5_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.10.15=h4a871b0_1_cpython
  - python_abi=3.10=5_cp310
  - pyzmq=26.2.0=py310h71f11fc_2
  - readline=8.2=h8228510_1
  - setuptools=75.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.1=py310ha75aee5_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.5=ha4adb4c_5
  - zipp=3.20.2=pyhd8ed1ab_0
  - pip:
      - absl-py==2.1.0
      - affine==2.4.0
      - aiobotocore==2.5.4
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.8
      - aioitertools==0.12.0
      - aiosignal==1.3.1
      - anndata==0.10.9
      - array-api-compat==1.9
      - asciitree==0.3.3
      - async-timeout==4.0.3
      - attrs==24.2.0
      - botocore==1.31.17
      - cellcharter==0.3.1
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - chex==0.1.87
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cloudpickle==3.0.0
      - colorcet==3.1.0
      - contextlib2==21.6.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - dask==2024.9.1
      - dask-expr==1.1.15
      - dask-image==2024.5.3
      - datashader==0.16.3
      - distributed==2024.9.1
      - docrep==0.3.2
      - et-xmlfile==1.1.0
      - etils==1.9.4
      - fasteners==0.19
      - filelock==3.16.1
      - flax==0.9.0
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - fsspec==2023.6.0
      - geopandas==1.0.1
      - h5py==3.12.1
      - humanize==4.10.0
      - idna==3.10
      - igraph==0.11.6
      - imageio==2.35.1
      - importlib-resources==6.4.5
      - inflect==7.4.0
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - legacy-api-wrap==1.4
      - leidenalg==0.10.2
      - lightning-utilities==0.11.7
      - llvmlite==0.43.0
      - locket==1.0.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - matplotlib-scalebar==0.8.1
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - mudata==0.3.1
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - multiscale-spatial-image==1.0.1
      - natsort==8.4.0
      - networkx==3.3
      - numba==0.60.0
      - numcodecs==0.13.0
      - numpy==1.26.4
      - numpyro==0.15.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - ome-zarr==0.9.0
      - omnipath==1.0.8
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optax==0.2.3
      - orbax-checkpoint==0.6.4
      - pandas==2.2.3
      - param==2.1.1
      - partd==1.4.2
      - patsy==0.5.6
      - pillow==10.4.0
      - pims==0.7
      - pooch==1.8.2
      - protobuf==5.28.2
      - pyarrow==17.0.0
      - pyct==0.5.0
      - pynndescent==0.5.13
      - pyogrio==0.10.0
      - pyparsing==3.1.4
      - pyproj==3.7.0
      - pyro-api==0.1.2
      - pyro-ppl==1.8.6
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.1.0
      - pytz==2024.2
      - pyyaml==6.0.2
      - rasterio==1.4.1
      - requests==2.32.3
      - rich==13.9.1
      - s3fs==2023.6.0
      - scanpy==1.10.3
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - scvi-tools==0.20.3
      - seaborn==0.13.2
      - session-info==1.0.0
      - shapely==2.0.6
      - sknw==0.15
      - slicerator==1.1.0
      - sortedcontainers==2.4.0
      - spatial-image==1.1.0
      - spatialdata==0.2.3
      - spatialdata-plot==0.2.6
      - squidpy==1.6.1
      - statsmodels==0.14.4
      - stdlib-list==0.10.0
      - sympy==1.13.3
      - tblib==3.0.0
      - tensorstore==0.1.66
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - toolz==0.12.1
      - torch==1.12.1+cu116
      - torchaudio==0.12.1+cu116
      - torchgmm==0.1.2
      - torchmetrics==1.4.2
      - torchvision==0.13.1+cu116
      - tqdm==4.66.5
      - triton==3.0.0
      - typeguard==4.3.0
      - tzdata==2024.2
      - umap-learn==0.5.6
      - urllib3==1.26.20
      - validators==0.34.0
      - wrapt==1.16.0
      - xarray==2024.9.0
      - xarray-dataclasses==1.8.0
      - xarray-datatree==0.0.14
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - yarl==1.13.1
      - zarr==2.18.3
      - zict==3.0.0
</details>

**Comment by marcovarrone** [comment]
Anything above 1.1.0 should be fine for `scvi-tools`, but the latest version (1.2.0) works as well!

Otherwise, if you want to make sure that everything is installed correctly you can create a new conda environment from scratch and follow the instructions.

**Comment by Bo-UT** [comment]
Great! 
I didn't realize you upgraded cellcharter. 
Now everything works great. The dependencies are: 
```
torch 2.6.0
pytorch-lightning 2.4.0
scvi-tools 1.2.0
```

Thanks again!
